services:
  product-service:
    build:
      context: ./ProductMS
    ports:
      - "8001:8080"
    env_file:
      - .env
  order-service:
    build:
      context: ./OrderMS
    ports:
      - "8002:8080"
    env_file:
      - .env
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver_db
    env_file:
      - .env
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
volumes:
  sql_data: